// Supabase utilities — barrel export
export { createClient } from "./client";
export { createClient as createServerClient } from "./server";
export { createAdminClient } from "./admin";
export type {
  Database,
  UserRole,
  MessageRole,
  DocumentCategory,
  PoamStatus,
  ImplementationStatus,
  SnapshotType,
  Profile,
  Conversation,
  Message,
  ComplianceDocument,
  DocumentChunk,
  NistControl,
  ScfControl,
  EvidenceEvaluation,
  IntelligenceSnapshot,
  ScfFrameworkMapping,
  ComplianceAssessment,
  PoamItem,
  ProfileInsert,
  ConversationInsert,
  MessageInsert,
  ComplianceDocumentInsert,
  DocumentChunkInsert,
  NistControlInsert,
  ScfControlInsert,
  EvidenceEvaluationInsert,
  IntelligenceSnapshotInsert,
  ScfFrameworkMappingInsert,
  ComplianceAssessmentInsert,
  PoamItemInsert,
  ProfileUpdate,
  ConversationUpdate,
  MessageUpdate,
  ComplianceDocumentUpdate,
  DocumentChunkUpdate,
  NistControlUpdate,
  ScfControlUpdate,
  EvidenceEvaluationUpdate,
  IntelligenceSnapshotUpdate,
  ScfFrameworkMappingUpdate,
  ComplianceAssessmentUpdate,
  PoamItemUpdate,
  // Threat Modeling types
  ThreatModelStatus,
  StrideCategory,
  SeverityLevel,
  StrideThreat,
  FmeaItem,
  ThreatModelData,
  ThreatModelSummary,
  ThreatModelRecord,
  ThreatModelReport,
  ThreatModelReportData,
} from "./types";

// Re-export STRIDE_LABELS constant
export { STRIDE_LABELS } from "./types";
