import { tool } from 'ai';
import { z } from 'zod';
import { ihosEngine } from '@/lib/ihos-engine/client';
import { getFrameworkScores } from '@/lib/data/compliance-data';
import * as standardApi from '@/lib/standard-api/client';

export const generateIntegratedDossier = tool({
  description:
    'Generate an Integrated Compliance Dossier for a specific product version. ' +
    'This orchestrates Threat Modeling, extracts top unmitigated risks, cross-references with current SCF posture, ' +
    'and calls the Standard API to find the optimal mitigation (ROI path) for missing controls. ' +
    'Returns a massive markdown-formatted audit report.',
  inputSchema: z.object({
    productVersionId: z.string().describe('The database ID of the product version (uuid)'),
    productVersionCode: z.string().describe('The human-readable version code, e.g. "2.2.1"'),
  }),
  execute: async (input) => {
    try {
      console.log(`[Dossier Tool] Generating integrated dossier for ${input.productVersionCode}...`);
      
      // 1. Generate Threat Model
      const threatModelResult = await ihosEngine.generateThreatModel({
        product_version: input.productVersionCode,
        target_frameworks: ['iso27001'],
        skip_grc_enrichment: true,
      }).catch(err => {
        console.warn('[Dossier Tool] Threat model generation failed:', err);
        return null;
      });

      const threats = threatModelResult?.threat_model?.threats || [];
      const criticalThreats = threats.filter((t: any) => (t.rpn || 0) >= 40 || t.stride_category === 'Spoofing');

      // 2. Fetch SCF Posture (Current Compliance State)
      const frameworkScores = await getFrameworkScores();
      const isoScore = frameworkScores.find(f => f.code === 'iso27001');

      // 3. Correlate (Mock mapping for demonstration of agentic intelligence)
      // Ideally we map STRIDE to SCF domains.
      const unmitigatedThreats = criticalThreats.map((t: any) => ({
        ...t,
        mitigationStatus: isoScore && isoScore.gapCount && isoScore.gapCount > 5 ? 'unmitigated' : 'partial',
      }));

      // 4. Proactive Standard API Resolution
      // For the top unmitigated threat, ask Standard API for the ROI path
      let roiPathData = null;
      if (unmitigatedThreats.length > 0) {
        try {
          // Ask the standard API for mitigation paths across target frameworks
          roiPathData = await standardApi.roiPath({
            target_frameworks: ['ISO 27001', 'NIST CSF'],
            top_n: 3,
          });
        } catch (apiErr) {
          console.warn('[Dossier Tool] Standard API roiPath failed:', apiErr);
        }
      }

      // 5. Draft the Markdown Dossier
      let dossier = `# Integrated Compliance Dossier: Version ${input.productVersionCode}\n\n`;
      dossier += `> **Generated by NCommand Lite Brain**\n\n`;

      dossier += `## 1. Current Posture (SCF / ISO 27001)\n`;
      if (isoScore) {
        dossier += `- **Score**: ${isoScore.score}%\n`;
        dossier += `- **Conforming**: ${isoScore.conformingCount}\n`;
        dossier += `- **Gaps**: ${isoScore.gapCount}\n\n`;
      } else {
        dossier += `No ISO 27001 posture data found.\n\n`;
      }

      dossier += `## 2. Threat Landscape (STRIDE)\n`;
      if (threats.length > 0) {
        dossier += `Generated ${threats.length} threats. **${criticalThreats.length} critical risks identified.**\n\n`;
        criticalThreats.slice(0, 3).forEach((t: any) => {
          dossier += `### ${t.title} (RPN: ${t.rpn})\n`;
          dossier += `- **Category**: ${t.stride_category}\n`;
          dossier += `- **Description**: ${t.description}\n`;
          dossier += `- **Component**: ${t.component}\n\n`;
        });
      } else {
        dossier += `Threat model generation unavailable or yielded no critical threats.\n\n`;
      }

      dossier += `## 3. Standard API Mitigation Crosswalk\n`;
      dossier += `Cross-referencing critical threats against market standards:\n\n`;
      
      if (roiPathData && roiPathData.roi_path && roiPathData.roi_path.length > 0) {
        dossier += `To close the identified gaps efficiently, adopt the following controls:\n`;
        roiPathData.roi_path.forEach((roi: any) => {
          dossier += `- **${roi.control_id}** (ROI Score: ${roi.roi_score})\n`;
          dossier += `  Mitigates: ${roi.key_mitigations?.join(', ')}\n`;
        });
      } else {
        dossier += `Could not retrieve standard API ROI paths for these threats.\n`;
      }

      return dossier;

    } catch (err) {
      console.warn('[Dossier Tool] Execution failed:', err);
      return `Failed to generate Integrated Dossier: ${(err as Error).message}`;
    }
  },
});
