-- ============================================================================
-- Migration 007: Agentic Evolution
-- ihOS — Intelligent Hardened Operating System
--
-- Creates tables and RLS policies for:
--   1. agent_goals              — GRC Remediation Projects / Goals
--   2. agent_tasks              — Technical execution tasks mapped to goals
--   3. agent_notifications      — Proactive compliance alerts & notifications
--   4. agent_learning_corrections — User feedback corrections to fine-tune prompts
--   5. agent_autonomy_boundaries — Autonomy boundaries per user/tenant
--   6. agent_org_state          — Dynamic organizational maturity & risk profiles
--
-- Dependencies: 003_core_tables, 005_rls_policies, 006_functions
-- ============================================================================

-- ──────────────────────────────────────────────────────────────────────────────
-- 1. AGENT_GOALS — GRC Remediation Projects
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.agent_goals (
    id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id        UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    framework_code VARCHAR     NOT NULL,
    title          TEXT        NOT NULL,
    description    TEXT        NULL,
    status         VARCHAR     NOT NULL DEFAULT 'not_started' CHECK (status IN ('not_started', 'in_progress', 'completed')),
    progress       INTEGER     NOT NULL DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.agent_goals IS 'GRC Remediation Projects / Goals for compliance framework gaps';
COMMENT ON COLUMN public.agent_goals.framework_code IS 'Framework code code (e.g. ISO_27001, SOC_2, NIST_800_53)';
COMMENT ON COLUMN public.agent_goals.status IS 'Status of the remediation goal';

CREATE INDEX idx_agent_goals_user ON public.agent_goals (user_id);
CREATE INDEX idx_agent_goals_framework ON public.agent_goals (framework_code);

-- ──────────────────────────────────────────────────────────────────────────────
-- 2. AGENT_TASKS — Technical Execution Tasks
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.agent_tasks (
    id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    goal_id        UUID        NOT NULL REFERENCES public.agent_goals(id) ON DELETE CASCADE,
    title          TEXT        NOT NULL,
    description    TEXT        NULL,
    status         VARCHAR     NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed')),
    deadline       TIMESTAMPTZ NULL,
    assigned_agent VARCHAR     NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.agent_tasks IS 'Technical execution tasks mapped to specific GRC goals';
COMMENT ON COLUMN public.agent_tasks.status IS 'Task status: pending, in_progress, completed';

CREATE INDEX idx_agent_tasks_goal ON public.agent_tasks (goal_id);
CREATE INDEX idx_agent_tasks_deadline ON public.agent_tasks (deadline);

-- ──────────────────────────────────────────────────────────────────────────────
-- 3. AGENT_NOTIFICATIONS — Proactive Alerts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.agent_notifications (
    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title      TEXT        NOT NULL,
    content    TEXT        NOT NULL,
    type       VARCHAR     NOT NULL CHECK (type IN ('poam_expiry', 'score_change', 'task_deadline')),
    read       BOOLEAN     NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.agent_notifications IS 'Logs of proactive alerts generated by agentic checks';
COMMENT ON COLUMN public.agent_notifications.type IS 'Category of alert: poam_expiry, score_change, task_deadline';

CREATE INDEX idx_agent_notifications_user_read ON public.agent_notifications (user_id, read);

-- ──────────────────────────────────────────────────────────────────────────────
-- 4. AGENT_LEARNING_CORRECTIONS — Feedback & Fine-tuning Loop
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.agent_learning_corrections (
    id                         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                    UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    conversation_id            UUID        NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
    message_id                 UUID        NULL REFERENCES public.messages(id) ON DELETE SET NULL,
    user_correction            TEXT        NOT NULL,
    agent_misaligned_response  TEXT        NOT NULL,
    learned_context            TEXT        NULL,
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.agent_learning_corrections IS 'Stores alignment feedback/corrections provided by users to tune agent context';

CREATE INDEX idx_agent_corrections_user ON public.agent_learning_corrections (user_id);

-- ──────────────────────────────────────────────────────────────────────────────
-- 5. AGENT_AUTONOMY_BOUNDARIES — Autonomy Zones (Green/Yellow/Red)
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.agent_autonomy_boundaries (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    action_type VARCHAR     NOT NULL,
    zone        VARCHAR     NOT NULL CHECK (zone IN ('green', 'yellow', 'red')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_action UNIQUE (user_id, action_type)
);

COMMENT ON TABLE public.agent_autonomy_boundaries IS 'Autonomy zone configuration per action type for the agent';
COMMENT ON COLUMN public.agent_autonomy_boundaries.zone IS 'green: autonomous, yellow: requires approval, red: forbidden';

CREATE INDEX idx_agent_autonomy_user ON public.agent_autonomy_boundaries (user_id);

-- ──────────────────────────────────────────────────────────────────────────────
-- 6. AGENT_ORG_STATE — Dynamic Organizational Context
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.agent_org_state (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    state_key   VARCHAR     NOT NULL,
    state_value JSONB       NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_state_key UNIQUE (user_id, state_key)
);

COMMENT ON TABLE public.agent_org_state IS 'Dynamic organizational data (e.g. risk levels, maturity score) for system prompts';

CREATE INDEX idx_agent_org_state_user ON public.agent_org_state (user_id);

-- ══════════════════════════════════════════════════════════════════════════════
-- ENABLE ROW LEVEL SECURITY
-- ══════════════════════════════════════════════════════════════════════════════
ALTER TABLE public.agent_goals                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_tasks                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_notifications        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_learning_corrections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_autonomy_boundaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_org_state            ENABLE ROW LEVEL SECURITY;

-- ══════════════════════════════════════════════════════════════════════════════
-- ROW LEVEL SECURITY POLICIES
-- ══════════════════════════════════════════════════════════════════════════════

-- agent_goals
CREATE POLICY goals_all_own ON public.agent_goals
    FOR ALL
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

CREATE POLICY goals_admin ON public.agent_goals
    FOR ALL
    USING (public.get_user_role() = 'admin');

-- agent_tasks
CREATE POLICY tasks_select_own ON public.agent_tasks
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.agent_goals g
            WHERE g.id = goal_id
              AND g.user_id = auth.uid()
        )
    );

CREATE POLICY tasks_insert_own ON public.agent_tasks
    FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.agent_goals g
            WHERE g.id = goal_id
              AND g.user_id = auth.uid()
        )
    );

CREATE POLICY tasks_update_own ON public.agent_tasks
    FOR UPDATE
    USING (
        EXISTS (
            SELECT 1 FROM public.agent_goals g
            WHERE g.id = goal_id
              AND g.user_id = auth.uid()
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.agent_goals g
            WHERE g.id = goal_id
              AND g.user_id = auth.uid()
        )
    );

CREATE POLICY tasks_delete_own ON public.agent_tasks
    FOR DELETE
    USING (
        EXISTS (
            SELECT 1 FROM public.agent_goals g
            WHERE g.id = goal_id
              AND g.user_id = auth.uid()
        )
    );

CREATE POLICY tasks_admin ON public.agent_tasks
    FOR ALL
    USING (public.get_user_role() = 'admin');

-- agent_notifications
CREATE POLICY notifications_all_own ON public.agent_notifications
    FOR ALL
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

CREATE POLICY notifications_admin ON public.agent_notifications
    FOR ALL
    USING (public.get_user_role() = 'admin');

-- agent_learning_corrections
CREATE POLICY corrections_all_own ON public.agent_learning_corrections
    FOR ALL
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

CREATE POLICY corrections_admin ON public.agent_learning_corrections
    FOR ALL
    USING (public.get_user_role() = 'admin');

-- agent_autonomy_boundaries
CREATE POLICY boundaries_all_own ON public.agent_autonomy_boundaries
    FOR ALL
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

CREATE POLICY boundaries_admin ON public.agent_autonomy_boundaries
    FOR ALL
    USING (public.get_user_role() = 'admin');

-- agent_org_state
CREATE POLICY org_state_all_own ON public.agent_org_state
    FOR ALL
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

CREATE POLICY org_state_admin ON public.agent_org_state
    FOR ALL
    USING (public.get_user_role() = 'admin');


-- ══════════════════════════════════════════════════════════════════════════════
-- TRIGGER FOR AUTO-CREATING BOUNDARIES ON NEW USER SIGNUP
-- ══════════════════════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    INSERT INTO public.profiles (id, role, created_at)
    VALUES (
        NEW.id,
        'ionic_user',
        now()
    );

    -- Insert default autonomy boundaries
    INSERT INTO public.agent_autonomy_boundaries (user_id, action_type, zone)
    VALUES
        (NEW.id, 'create_goal', 'yellow'),
        (NEW.id, 'send_alert', 'green'),
        (NEW.id, 'update_task_status', 'yellow')
    ON CONFLICT (user_id, action_type) DO NOTHING;

    RETURN NEW;
END;
$$;

-- Seed default autonomy boundaries for existing users/profiles
INSERT INTO public.agent_autonomy_boundaries (user_id, action_type, zone)
SELECT p.id, d.action_type, d.zone
FROM public.profiles p
CROSS JOIN (
    VALUES
        ('create_goal', 'yellow'),
        ('send_alert', 'green'),
        ('update_task_status', 'yellow')
) AS d(action_type, zone)
ON CONFLICT (user_id, action_type) DO NOTHING;

-- Apply set_updated_at triggers for goals and tasks
CREATE TRIGGER trg_agent_goals_updated_at
    BEFORE UPDATE ON public.agent_goals
    FOR EACH ROW
    EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_agent_tasks_updated_at
    BEFORE UPDATE ON public.agent_tasks
    FOR EACH ROW
    EXECUTE FUNCTION public.set_updated_at();

